//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mednote.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mednote.Client.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mednote is a medical voice recognition and transcription program that uses Google Cloud Speech-to-Text for transcription and ChatGPT for processing..
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API configuration error.
        /// </summary>
        internal static string ApiConfigurationError {
            get {
                return ResourceManager.GetString("ApiConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API connected.
        /// </summary>
        internal static string ApiConnected {
            get {
                return ResourceManager.GetString("ApiConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Connection.
        /// </summary>
        internal static string ApiConnectionSection {
            get {
                return ResourceManager.GetString("ApiConnectionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API disconnected.
        /// </summary>
        internal static string ApiDisconnected {
            get {
                return ResourceManager.GetString("ApiDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mednote.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Devices.
        /// </summary>
        internal static string AudioDevicesSection {
            get {
                return ResourceManager.GetString("AudioDevicesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Recording.
        /// </summary>
        internal static string AudioRecordingTitle {
            get {
                return ResourceManager.GetString("AudioRecordingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start transcription after recording stops.
        /// </summary>
        internal static string AutoStartTranscription {
            get {
                return ResourceManager.GetString("AutoStartTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTranscription {
            get {
                return ResourceManager.GetString("CancelTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved..
        /// </summary>
        internal static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check connection.
        /// </summary>
        internal static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking API status....
        /// </summary>
        internal static string CheckingAPI {
            get {
                return ResourceManager.GetString("CheckingAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear temporary files.
        /// </summary>
        internal static string ClearTempFiles {
            get {
                return ResourceManager.GetString("ClearTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recording is undergoing. Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmExitRecording {
            get {
                return ResourceManager.GetString("ConfirmExitRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        internal static string ConfirmExitTitle {
            get {
                return ResourceManager.GetString("ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy processed text.
        /// </summary>
        internal static string CopyProcessedText {
            get {
                return ResourceManager.GetString("CopyProcessedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy raw text.
        /// </summary>
        internal static string CopyRawText {
            get {
                return ResourceManager.GetString("CopyRawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mednote - all rights reserved, created by Dennis Enström.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string CreatedLabel {
            get {
                return ResourceManager.GetString("CreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording {0:yyyy-MM-dd HH:mm}.
        /// </summary>
        internal static string DefaultRecordingTitle {
            get {
                return ResourceManager.GetString("DefaultRecordingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the transcription &apos;{0}&apos;? Both the audio file and the transcription will be permanently deleted..
        /// </summary>
        internal static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        internal static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTranscription {
            get {
                return ResourceManager.GetString("DeleteTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit information.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error choosing storage directory: {0}.
        /// </summary>
        internal static string ErrorBrowsingDirectory {
            get {
                return ResourceManager.GetString("ErrorBrowsingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing temporary files: {0}.
        /// </summary>
        internal static string ErrorClearingTempFiles {
            get {
                return ResourceManager.GetString("ErrorClearingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying text: {0}.
        /// </summary>
        internal static string ErrorCopyingText {
            get {
                return ResourceManager.GetString("ErrorCopyingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the transcription..
        /// </summary>
        internal static string ErrorDeleteFailed {
            get {
                return ResourceManager.GetString("ErrorDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting transcription: {0}.
        /// </summary>
        internal static string ErrorDeletingTranscription {
            get {
                return ResourceManager.GetString("ErrorDeletingTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serious error has occurred and the program must close: {0}.
        /// </summary>
        internal static string ErrorFatal {
            get {
                return ResourceManager.GetString("ErrorFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        internal static string ErrorFatalTitle {
            get {
                return ResourceManager.GetString("ErrorFatalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file could not be found.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings: {0}.
        /// </summary>
        internal static string ErrorLoadingSettings {
            get {
                return ResourceManager.GetString("ErrorLoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading transcription: {0}.
        /// </summary>
        internal static string ErrorLoadingTranscription {
            get {
                return ResourceManager.GetString("ErrorLoadingTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading transcriptions: {0}.
        /// </summary>
        internal static string ErrorLoadingTranscriptions {
            get {
                return ResourceManager.GetString("ErrorLoadingTranscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No microphone found..
        /// </summary>
        internal static string ErrorNoMicrophone {
            get {
                return ResourceManager.GetString("ErrorNoMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording to transcribe..
        /// </summary>
        internal static string ErrorNoRecording {
            get {
                return ResourceManager.GetString("ErrorNoRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No speaker found..
        /// </summary>
        internal static string ErrorNoSpeaker {
            get {
                return ResourceManager.GetString("ErrorNoSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription could not be found..
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error pausing/resuming recording: {0}.
        /// </summary>
        internal static string ErrorPausingRecording {
            get {
                return ResourceManager.GetString("ErrorPausingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error playing audio: {0}.
        /// </summary>
        internal static string ErrorPlayingAudio {
            get {
                return ResourceManager.GetString("ErrorPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting settings: {0}.
        /// </summary>
        internal static string ErrorResettingSettings {
            get {
                return ResourceManager.GetString("ErrorResettingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving changes: {0}.
        /// </summary>
        internal static string ErrorSavingChanges {
            get {
                return ResourceManager.GetString("ErrorSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings: {0}.
        /// </summary>
        internal static string ErrorSavingSettings {
            get {
                return ResourceManager.GetString("ErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse server response.
        /// </summary>
        internal static string ErrorServerResponse {
            get {
                return ResourceManager.GetString("ErrorServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start recording: {0}.
        /// </summary>
        internal static string ErrorStartingRecording {
            get {
                return ResourceManager.GetString("ErrorStartingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during program startup: {0}.
        /// </summary>
        internal static string ErrorStartupFailed {
            get {
                return ResourceManager.GetString("ErrorStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        internal static string ErrorStartupTitle {
            get {
                return ResourceManager.GetString("ErrorStartupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping recording: {0}.
        /// </summary>
        internal static string ErrorStoppingRecording {
            get {
                return ResourceManager.GetString("ErrorStoppingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find or create storage directory..
        /// </summary>
        internal static string ErrorStorageDirectory {
            get {
                return ResourceManager.GetString("ErrorStorageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing timed out..
        /// </summary>
        internal static string ErrorTimeoutProcessing {
            get {
                return ResourceManager.GetString("ErrorTimeoutProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription timed out. The audio file may be too large..
        /// </summary>
        internal static string ErrorTimeoutTranscription {
            get {
                return ResourceManager.GetString("ErrorTimeoutTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error transcribing: {0}.
        /// </summary>
        internal static string ErrorTranscribing {
            get {
                return ResourceManager.GetString("ErrorTranscribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating audio devices: {0}.
        /// </summary>
        internal static string ErrorUpdatingDevices {
            get {
                return ResourceManager.GetString("ErrorUpdatingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error viewing transcription details: {0}.
        /// </summary>
        internal static string ErrorViewingDetails {
            get {
                return ResourceManager.GetString("ErrorViewingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File information.
        /// </summary>
        internal static string FileInfoTab {
            get {
                return ResourceManager.GetString("FileInfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path:.
        /// </summary>
        internal static string FilePathLabel {
            get {
                return ResourceManager.GetString("FilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0}.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryTab {
            get {
                return ResourceManager.GetString("HistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription History.
        /// </summary>
        internal static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone device.
        /// </summary>
        internal static string InputDeviceLabel {
            get {
                return ResourceManager.GetString("InputDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection..
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text to copy..
        /// </summary>
        internal static string NoTextToCopy {
            get {
                return ResourceManager.GetString("NoTextToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transcription available. Start a recording first..
        /// </summary>
        internal static string NoTranscriptionAvailable {
            get {
                return ResourceManager.GetString("NoTranscriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transcriptions available..
        /// </summary>
        internal static string NoTranscriptionsAvailable {
            get {
                return ResourceManager.GetString("NoTranscriptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker device.
        /// </summary>
        internal static string OutputDeviceLabel {
            get {
                return ResourceManager.GetString("OutputDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID:.
        /// </summary>
        internal static string PatientIdLabel {
            get {
                return ResourceManager.GetString("PatientIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Recording.
        /// </summary>
        internal static string PauseRecording {
            get {
                return ResourceManager.GetString("PauseRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string PlayAudio {
            get {
                return ResourceManager.GetString("PlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback device in use by another program..
        /// </summary>
        internal static string PlaybackDeviceInUse {
            get {
                return ResourceManager.GetString("PlaybackDeviceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing audio....
        /// </summary>
        internal static string PreparingAudio {
            get {
                return ResourceManager.GetString("PreparingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed text from ChatGPT.
        /// </summary>
        internal static string ProcessedTextHeader {
            get {
                return ResourceManager.GetString("ProcessedTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed text.
        /// </summary>
        internal static string ProcessedTextTab {
            get {
                return ResourceManager.GetString("ProcessedTextTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string ProcessingStatus {
            get {
                return ResourceManager.GetString("ProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw transcription from Google.
        /// </summary>
        internal static string RawTranscriptionHeader {
            get {
                return ResourceManager.GetString("RawTranscriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw transcription.
        /// </summary>
        internal static string RawTranscriptionTab {
            get {
                return ResourceManager.GetString("RawTranscriptionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved processed text.
        /// </summary>
        internal static string ReceivedProcessedText {
            get {
                return ResourceManager.GetString("ReceivedProcessedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved transcription.
        /// </summary>
        internal static string ReceivedTranscription {
            get {
                return ResourceManager.GetString("ReceivedTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone is already in use by another program..
        /// </summary>
        internal static string RecordingDeviceInUse {
            get {
                return ResourceManager.GetString("RecordingDeviceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording duration: {0}.
        /// </summary>
        internal static string RecordingDuration {
            get {
                return ResourceManager.GetString("RecordingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the record button to start a new recording. After stopping the recording, press &apos;Start Transcription&apos; to send the audio to Google for transcription and processing with ChatGPT..
        /// </summary>
        internal static string RecordingHelpText {
            get {
                return ResourceManager.GetString("RecordingHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the record button to start.
        /// </summary>
        internal static string RecordingInstructions {
            get {
                return ResourceManager.GetString("RecordingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string RecordingPaused {
            get {
                return ResourceManager.GetString("RecordingPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        internal static string RecordingStatus {
            get {
                return ResourceManager.GetString("RecordingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording stopped.
        /// </summary>
        internal static string RecordingStopped {
            get {
                return ResourceManager.GetString("RecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string RecordingTab {
            get {
                return ResourceManager.GetString("RecordingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Conversation.
        /// </summary>
        internal static string RecordingTitle {
            get {
                return ResourceManager.GetString("RecordingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording title.
        /// </summary>
        internal static string RecordingTitleHint {
            get {
                return ResourceManager.GetString("RecordingTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh device list.
        /// </summary>
        internal static string RefreshDevices {
            get {
                return ResourceManager.GetString("RefreshDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshList {
            get {
                return ResourceManager.GetString("RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings to default values?.
        /// </summary>
        internal static string ResetConfirmMessage {
            get {
                return ResourceManager.GetString("ResetConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm reset.
        /// </summary>
        internal static string ResetConfirmTitle {
            get {
                return ResourceManager.GetString("ResetConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        internal static string ResetDefaultsButton {
            get {
                return ResourceManager.GetString("ResetDefaultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings reset..
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Recording.
        /// </summary>
        internal static string ResumeRecording {
            get {
                return ResourceManager.GetString("ResumeRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retranscribe.
        /// </summary>
        internal static string RetranscribeButton {
            get {
                return ResourceManager.GetString("RetranscribeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to retranscribe? This will replace the existing transcription..
        /// </summary>
        internal static string RetranscribeConfirmMessage {
            get {
                return ResourceManager.GetString("RetranscribeConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm retranscription.
        /// </summary>
        internal static string RetranscribeConfirmTitle {
            get {
                return ResourceManager.GetString("RetranscribeConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retranscribe from the audio recording.
        /// </summary>
        internal static string RetranscribeTooltip {
            get {
                return ResourceManager.GetString("RetranscribeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        internal static string SavedSettings {
            get {
                return ResourceManager.GetString("SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save raw recording (original without conversion).
        /// </summary>
        internal static string SaveRawAudio {
            get {
                return ResourceManager.GetString("SaveRawAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SaveSettingsButton {
            get {
                return ResourceManager.GetString("SaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving recording....
        /// </summary>
        internal static string SavingRecording {
            get {
                return ResourceManager.GetString("SavingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search transcriptions.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending to ChatGPT for processing....
        /// </summary>
        internal static string SendingToChatGPT {
            get {
                return ResourceManager.GetString("SendingToChatGPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending to Google Speech-to-Text....
        /// </summary>
        internal static string SendingToGoogle {
            get {
                return ResourceManager.GetString("SendingToGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error: {0}.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unavailable. Check your connection..
        /// </summary>
        internal static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Transcription.
        /// </summary>
        internal static string StartTranscription {
            get {
                return ResourceManager.GetString("StartTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not completed.
        /// </summary>
        internal static string StatusNotCompleted {
            get {
                return ResourceManager.GetString("StatusNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback.
        /// </summary>
        internal static string StopPlayback {
            get {
                return ResourceManager.GetString("StopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording storage folder.
        /// </summary>
        internal static string StorageDirectoryHint {
            get {
                return ResourceManager.GetString("StorageDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        internal static string StorageSection {
            get {
                return ResourceManager.GetString("StorageSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary files cleared..
        /// </summary>
        internal static string TempFilesCleared {
            get {
                return ResourceManager.GetString("TempFilesCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text copied to clipboard..
        /// </summary>
        internal static string TextCopied {
            get {
                return ResourceManager.GetString("TextCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribing....
        /// </summary>
        internal static string TranscribingStatus {
            get {
                return ResourceManager.GetString("TranscribingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription cancelled.
        /// </summary>
        internal static string TranscriptionCancelled {
            get {
                return ResourceManager.GetString("TranscriptionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription completed.
        /// </summary>
        internal static string TranscriptionCompleted {
            get {
                return ResourceManager.GetString("TranscriptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Details.
        /// </summary>
        internal static string TranscriptionDetailsTitle {
            get {
                return ResourceManager.GetString("TranscriptionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription ID:.
        /// </summary>
        internal static string TranscriptionIdLabel {
            get {
                return ResourceManager.GetString("TranscriptionIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Options.
        /// </summary>
        internal static string TranscriptionOptionsSection {
            get {
                return ResourceManager.GetString("TranscriptionOptionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported audio format.
        /// </summary>
        internal static string UnsupportedAudioFormat {
            get {
                return ResourceManager.GetString("UnsupportedAudioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
